### ISSUE TITLE
White tiles displayed when too many rows

### ISSUE THREAD

**Issue by ansonrel** [federicomarini/bettr#10]
Hi, 

Some of our instances running `bettr` are becoming very populated and one of them displays white tiles instead of the score-related color (see http://imlspenticton.uzh.ch:3840/omni_clustering/). The input data does have non-zero value so I guess it is because of the number of rows in the data. Also when I stretch the plot manually it does eventually show the content of the tiles. 

Is there a way to fix this or is it inherent to the display of heatmaps with large amount of rows... ? 
Thanks!

**Comment by csoneson** [comment]
Oh, indeed that does not look good at all. I have removed the white cell borders in the heatmap and pushed a new version to the `large-heatmap-adaptations` branch. I also added a checkbox to remove the row names of the heatmap (to fix #9). Would this address the issue?

**Comment by csoneson** [comment]
Excellent - I'll merge this into the `master` branch then.
