### ISSUE TITLE
Incompatibility for 1 metric data

### ISSUE THREAD

**Issue by ansonrel** [federicomarini/bettr#13]
Hi, 

I don't know if it is an 'issue' per se but I think that currently `bettr` doesn't handle inputs with only 1 metric (I guess that in normal cases one would have more than 1). What happens is an error like this: 

```
Warning: Error in .subset2(x, "impl")$outputOptions: metric_ARI_transformUI is not in list of output objects
  54: stop
  53: .subset2(x, "impl")$outputOptions
  52: shiny::outputOptions
  51: FUN
  50: lapply
  49: server
Error in .subset2(x, "impl")$outputOptions(name, ...) : 
  metric_ARI_transformUI is not in list of output objects
```

From a quick look at a debug session, it seems that some dataframe subsetting create vectors instead of dataframe and this propagates to the input of the shiny app. 
I'm not sure if `bettr` is intended to these special case scenarios so maybe I would suggest a warning message ...?

**Comment by csoneson** [comment]
Good catch - I think this should definitely be supported (even without a warning). I'll look into it.

**Comment by csoneson** [comment]
Ok, I pushed v0.1.2 (to the `master` branch), I think that should fix it.

**Comment by ansonrel** [comment]
It works perfectly now, thank you so much!
