### ISSUE TITLE
Remove display of rownames

### ISSUE THREAD

**Issue by ansonrel** [federicomarini/bettr#9]
Hi, 
Would it be possible to remove or mask the rownames in the `Heatmap` panel of bettr ? 

For instance [here](http://imlspenticton.uzh.ch:3840/omni_clustering/), we have quite a lot of combinations and it hinders the readability/ aesthetics. I've tried to remove the rownames from the input data but then it cannot link the rows to their metadata. 

Thanks!

**Comment by csoneson** [comment]
I agree, we can have an option to display the row names or not in the heatmap. While you can make the figure panel as large as you want, it may be unreadable regardless.
